
// Keep detailed results available through one disclosure, with four primary sections.
A.investment_plan={...A.investment_plan,default_profile:'focus',preferred_style:'Your focused portfolio',profile_labels:{focus:'Your allocation · NVDA / TSM / MU / SPY',lower:'Reserve comparison · 25% equities'},profiles:{focus:{safe_idr:0,nvda:.40,tsm:.25,mu:.20,spy:.15},lower:{safe_idr:.75,nvda:.10,tsm:.0625,mu:.05,spy:.0375}}};
const entry=A.entry_snapshot,plan=A.investment_plan,quoteMap=Object.fromEntries(entry.quotes.filter(q=>!q.error).map(q=>[q.symbol.toLowerCase(),q]));
const simpleInvestmentIds=['nvda','tsm','mu','spy'];
const detailedViews=[...document.querySelectorAll('.view')];
detailedViews.forEach(node=>{node.hidden=true;$('advanced-content').appendChild(node)});
function simpleShow(id){document.querySelectorAll('.simple-view').forEach(n=>n.hidden=n.id!==id);document.querySelectorAll('[data-simple]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.simple===id)))}
function detailShow(id){
 if(!detailedViews.some(n=>n.id===id))return;
 simpleShow('simple-research');$('advanced-details').open=true;$('advanced-section').value=id;detailedViews.forEach(n=>n.hidden=n.id!==id);
 if(id==='indices'&&!$('index-frame').getAttribute('srcdoc'))$('index-frame').srcdoc=payload.index_html;
 if(id==='nvda'&&!$('nvda-frame').getAttribute('srcdoc'))$('nvda-frame').srcdoc=payload.nvda_html;
 if(id==='data'&&!$('analysis-json').value)$('analysis-json').value=JSON.stringify(A,null,2);
}
show=detailShow;
openTicker=function(value){const query=value.trim().toLowerCase(),id=({'s&p 500':'sp500','s&p':'sp500','^gspc':'sp500','^ixic':'nasdaq','^jkse':'ihsg'})[query]||ids.find(id=>id===query||names[id].toLowerCase()===query);if(!id)return;if(simpleInvestmentIds.includes(id)){$('simple-stock-select').value=id;simpleStock();simpleShow('simple-stocks')}else simpleShow('simple-markets')};
const simpleMoney=(v,currency='IDR')=>currency==='IDR'?'Rp'+num(v,0):'$'+num(v,2);
function selectedPlan(){
 const fixed=$('plan-deadline').value==='fixed';const profile=fixed?'lower':$('plan-risk').value;
 return {fixed,profile,weights:plan.profiles[profile]};
}
function renderSimplePlan(){
 const {fixed,profile,weights}=selectedPlan(),budget=Number($('plan-budget').value),fx=Number($('plan-fx').value),monthly=Number($('plan-monthly').value),validBudget=Number.isFinite(budget)&&budget>0,validFx=Number.isFinite(fx)&&fx>0,eq=1-weights.safe_idr;
 $('pro-portfolio-context').textContent='IDR → US · 3–5 years · '+(plan.profile_labels?.[profile]||'Portfolio comparison');
 const concentrated=profile==='focus'||profile==='aggressive'||profile==='moderate',semi=Object.entries(weights).filter(([id])=>['tsm','nvda','amd','mu','intc'].includes(id)).reduce((sum,[,weight])=>sum+weight,0);
 $('plan-decision').innerHTML='<p><strong>'+pct(eq)+' US equities · '+pct(weights.safe_idr)+' defensive IDR reserve</strong></p><p class="quiet">'+(fixed?'A fixed three-year deadline overrides the higher-risk choice. Protect the full amount you must spend first; only surplus money belongs in equities. This lower-exposure mix is an illustration for that surplus.':concentrated?(profile==='focus'?'Your allocation: NVDA 40%, TSM 25%, MU 20%, SPY 15%.':profile==='aggressive'?'Aggressive and concentrated.':'Moderately aggressive and concentrated.')+' Direct semiconductor positions are '+pct(semi)+' of total investable money ('+pct(semi/eq)+' of equities), before ETF overlap. You accepted losses beyond 30%; this is not a loss limit. The severe market/FX example below loses '+pct(Math.abs(weights.spy*-.55+semi*-.685))+'.':profile==='lower'?'Cautious comparison: a broad index fund with a small semiconductor sleeve. This preserves the previous illustration for comparison; it does not cap losses at 15%.':'Balanced comparison: half in US stocks, half in the spending currency. Losses can still exceed 30% under a worse market or currency shock.')+'</p><p class="source-inline">Illustrative weights chosen to demonstrate your style, not model-optimized allocations or buy ratings. Current prices alone do not establish attractive valuation.</p>';
 const labels={safe_idr:'Defensive reserve in IDR',spy:'S&P 500 fund (SPY reference)',tsm:'TSM · foundry',nvda:'NVDA · AI compute',mu:'MU · memory cycle',amd:'AMD · growth exposure'};
 $('plan-allocation-bar').innerHTML=Object.entries(weights).map(([id,w])=>'<span title="'+esc(labels[id]+' '+pct(w))+'" style="width:'+w*100+'%;background:'+(colors[id]||'#708198')+'"></span>').join('');
 $('plan-allocation').innerHTML=table(['Allocation','% of total budget',...(validBudget?['Illustrative IDR amount']:[])],Object.entries(weights).filter(([,w])=>w>0).map(([id,w])=>[labels[id],pct(w),...(validBudget?[simpleMoney(budget*w)]:[])]));
 $('plan-schedule').innerHTML=table(['Month','% of intended equity allocation',...(validBudget?['IDR to convert','Estimated USD']:[])],plan.entry_months.map((month,i)=>[month,pct(plan.entry_fractions[i]),...(validBudget?[simpleMoney(budget*eq*plan.entry_fractions[i]),validFx?simpleMoney(budget*eq*plan.entry_fractions[i]/fx,'USD'):'Enter a valid FX rate']:[])]));
 const equityBudget=budget*eq,first=equityBudget*.25;
 $('plan-budget-reading').innerHTML=!validFx?'<p>Enter a positive IDR/USD rate to calculate currency amounts.</p>':validBudget?'<p>Intended equity sleeve: <strong>'+simpleMoney(equityBudget)+'</strong> ≈ '+simpleMoney(equityBudget/fx,'USD')+'. First purchase: '+simpleMoney(first)+' ≈ '+simpleMoney(first/fx,'USD')+'.</p>'+(monthly>0?'<p>Each monthly contribution: '+simpleMoney(monthly*eq)+' toward US equities and '+simpleMoney(monthly*weights.safe_idr)+' toward the IDR reserve. Estimated equity conversion: '+simpleMoney(monthly*eq/fx,'USD')+'.</p>':''):'<p>Enter a budget to calculate the first purchase and monthly schedule. The percentages apply to your investable money, after required spending is set aside.</p>';
 const shocks=[['Broad market correction',-.25,-.40,0],['Deep sell-off plus stronger IDR',-.50,-.65,-.10],['Deeper sell-off plus stronger IDR',-.60,-.75,-.15]];
 const riskySector=eq-weights.spy;
 $('plan-stress').innerHTML=table(['Illustrative shock','Core USD return','Semiconductor USD return','USD/IDR change','Portfolio IDR return'],shocks.map(([name,core,sector,fxchange])=>[name,pct(core),pct(sector),pct(fxchange),pct(weights.spy*((1+core)*(1+fxchange)-1)+riskySector*((1+sector)*(1+fxchange)-1))]));
 renderSimpleQuotes();simpleStock();
}
function currentQuote(id){const q=quoteMap[id];return q?.latest_minute_bar?{price:q.latest_minute_bar.price,time:q.latest_minute_bar.time_wib,session:q.latest_minute_bar.after_regular_session?'After hours':'Feed bar',q}:q?{price:q.price,time:q.quote_time_wib,session:'Regular session',q}:null}
function renderSimpleQuotes(){
 const fx=Number($('plan-fx').value),validFx=Number.isFinite(fx)&&fx>0;
 $('simple-quotes').innerHTML=table(['Investment','Regular close, USD','Latest bar, USD','Time, WIB','Estimated IDR / share'],simpleInvestmentIds.map(id=>{const c=currentQuote(id),q=c.q;return['<button class="quote-open" data-investment="'+id+'">'+id.toUpperCase()+'</button>',simpleMoney(q.price,'USD'),simpleMoney(c.price,'USD'),c.time.slice(11,19),validFx?simpleMoney(c.price*fx):'—']}));
 $('simple-quote-status').textContent='Latest retrieved one-minute bars: 1 October 2026, around 04:10–04:11 WIB (30 September US after-hours session). Regular closes are from around 03:00 WIB. Saved snapshot, not guaranteed exchange real-time or an order price.';
 const fxq=quoteMap['idr=x'];$('simple-fx-status').innerHTML='BI daily reference: Rp'+num(entry.fx_reference.idr_per_usd,0)+'/USD on '+entry.fx_reference.date+'. Public FX feed: Rp'+num(fxq.price,0)+'/USD at '+fxq.quote_time_wib.slice(0,19).replace('T',' ')+' WIB; that older quote is not treated as live. <a href="'+entry.fx_reference.source+'" target="_blank" rel="noreferrer">BI source</a>.';
 $('simple-quote-sources').innerHTML=table(['Symbol','Timestamp, WIB','Source'],simpleInvestmentIds.map(id=>{const c=currentQuote(id);return[id.toUpperCase(),c.time,'<a href="'+esc(c.q.source_url)+'" target="_blank" rel="noreferrer">Retained Yahoo feed endpoint</a>']}));
 document.querySelectorAll('.quote-open').forEach(n=>n.addEventListener('click',()=>{$('simple-stock-select').value=n.dataset.investment;simpleStock();simpleShow('simple-stocks')}));
}
function simpleStock(){
 const id=$('simple-stock-select').value||'spy',a=A.assets[id],c=currentQuote(id),fx=Number($('plan-fx').value),{weights}=selectedPlan();
 $('simple-stock-metrics').innerHTML=[['Latest retrieved USD',simpleMoney(c.price,'USD')],['Estimated IDR / share',Number.isFinite(fx)&&fx>0?simpleMoney(c.price*fx):'—'],['Illustrative budget weight',pct(weights[id]||0)],['Historical maximum drawdown',pct(a.max_drawdown)]].map(([label,value])=>'<div class="metric"><div class="label">'+label+'</div><div class="value">'+value+'</div></div>').join('');
 const roles={spy:'Core holding. Broad S&P 500 exposure is the starting point of this plan. It still carries equity and USD/IDR risk; its existing technology holdings overlap with the individual stock sleeve.',tsm:'Small satellite. Foundry exposure adds a different semiconductor business, but fabrication spending, ADR/currency differences and geographic concentration matter. The retained annual filings are in TWD, while this quote is a USD ADR.',nvda:'Small satellite. AI-compute exposure remains a concentrated stock risk, even with strong historical earnings. The core fund can already hold NVDA; the direct position is additional exposure.',mu:'Small, conditional satellite. Memory earnings are cyclical, and the 30 September earnings event is newer than the report’s fundamentals. This after-hours price is refreshed, but the official new release could not be retrieved here. Review that release before adding; do not treat the old annualized-quarter multiple as a current valuation.',amd:'Small satellite. Keep the position limited because valuation depends heavily on future growth and execution. The GAAP multiple is distinct from company adjusted EPS; neither supplies a precise entry signal.',intc:'Watchlist. No allocation in this starting plan. The retained GAAP TTM is loss-making; price/earnings is undefined. A turnaround needs separate evidence on margins, cash flow and capital spending before a position is justified.',qqq:'Optional alternative exposure. No separate allocation in this starting plan because it adds substantial growth/technology overlap to the core and semiconductor stocks. If used, replace part of the core allocation rather than adding extra stock exposure.'};
 const focusedRoles={spy:'Diversification sleeve. The concentrated illustration gives this fund a supporting role. Its technology holdings can overlap with the direct stock positions; fund holdings have not been looked through in this report.',tsm:'Concentrated foundry position. The example assigns a large weight, so geographic concentration, fabrication spending and valuation matter substantially. Annual statements are in TWD while this is a USD ADR quote. The target is illustrative, not a current buy rating.',nvda:'Concentrated AI-compute position. A large direct position adds business, valuation and execution risk beyond the fund’s overlapping holdings. Review the latest filings and thesis before deploying the example weight.',amd:'Growth position. Future growth, competitive execution and valuation drive the thesis. The retained GAAP multiple differs from adjusted EPS; neither produces a precise entry signal. This is an illustrative concentrated allocation.',mu:'Conditional watchlist; no weight in the concentrated examples. The retained financial inputs precede the 30 September earnings event. Review and incorporate the new official results before considering a funded position; refreshed price arithmetic is not a refreshed valuation.',intc:'Turnaround watchlist; no weight in the concentrated examples. Loss-making retained GAAP earnings and capital spending require separate evidence on cash flow and margin recovery before adding exposure.',qqq:'Watchlist alternative; no extra allocation. This growth fund can increase overlap with the semiconductor positions. If used, replace another allocation rather than adding exposure above the intended equity budget.'};
 const activeProfile=selectedPlan().profile;Object.assign(focusedRoles,{nvda:'40% target. Your largest position: compute platforms, software and networking. SPY may add overlapping exposure; look-through holdings have not been measured.',tsm:'25% target. Manufacturing and advanced packaging; USD ADR with five ordinary shares per ADR. Taiwan, customer demand, execution and entry valuation remain key risks.',mu:'20% target. Memory and HBM demand, cash conversion and cycle normalization. The investment decision workspace includes the 30 September fiscal-year release; older options remain separately dated.',spy:'15% target. S&P 500 ETF exposure alongside the three stocks. It remains an equity holding and can overlap with NVDA and MU; it is not cash or a loss cap.'});const role=(activeProfile==='focus'||activeProfile==='aggressive'||activeProfile==='moderate')?focusedRoles[id]:roles[id];
 $('simple-stock-reading').innerHTML='<p><strong>'+id.toUpperCase()+' · '+esc(c.session)+'</strong> <span class="quiet">'+esc(c.time.slice(0,19).replace('T',' '))+' WIB</span></p><p class="quiet">'+esc(role)+'</p>';
 const rows=a.history.filter(q=>q.date>='2021-09-29'),base=rows[0].level;plot('simple-stock-history',[{color:colors[id],points:rows.map(q=>({date:q.date,value:q.level/base}))}],v=>num(v)+'×',true);
 const f=R.filings[id];
 if(f){const t=f.ttm,eps=t?.eps,pe=id!=='tsm'&&eps>0?c.price/eps:null;$('simple-stock-facts').innerHTML=table(['Retained financial measure','Value'],[['Latest statement period',f.latest_period.end],['Statement currency',f.currency],['Quarterly-summed GAAP TTM EPS',eps==null?'Unavailable':num(eps)],['Latest quote / retained TTM GAAP EPS',pe==null?'Undefined / unavailable':num(pe)+'×'],['Latest gross margin',pct(f.latest_period.gross_margin)]]);$('simple-stock-filing-note').textContent='Statement availability cutoff: 29 September. This arithmetic updates the price numerator only; earnings inputs are retained. '+(id==='mu'?'MU’s post-30-September results are not included.':id==='tsm'?'USD ADR price is kept separate from annual TWD ordinary-share EPS.':'The latest quote can move after the saved capture.');}
 else{$('simple-stock-facts').innerHTML=table(['Retained history','Value'],[['Return basis',esc(a.basis)],['Model history cutoff',a.last],['Full-sample volatility',pct(a.volatility)],['Historical maximum drawdown',pct(a.max_drawdown)]]);$('simple-stock-filing-note').textContent=id==='nvda'?'Complete retained NVDA financials and source definitions remain in the detailed module.':'A fund is a portfolio of companies; one corporate earnings multiple is not a complete fund valuation. The detailed report retains the comparative history.';}
}
function simpleMarkets(){const selection=$('simple-market-select').value==='indices'?['sp500','nasdaq','ihsg']:simpleInvestmentIds;plot('simple-market-history',selection.map(id=>{const rows=A.assets[id].history.filter(q=>q.date>='2021-09-29'),base=rows[0].level;return{color:colors[id],points:rows.map(q=>({date:q.date,value:q.level/base}))}}),v=>num(v)+'×',true);$('simple-market-history').insertAdjacentHTML('afterbegin','<div class="legend">'+selection.map(id=>'<span style="color:'+colors[id]+'">'+esc(names[id])+'</span>').join('')+'</div>')}
document.querySelectorAll('[data-simple]').forEach(n=>n.addEventListener('click',()=>simpleShow(n.dataset.simple)));
$('advanced-section').addEventListener('change',()=>detailShow($('advanced-section').value));$('advanced-details').addEventListener('toggle',()=>{if($('advanced-details').open&&detailedViews.every(n=>n.hidden))detailShow($('advanced-section').value)});
$('simple-stock-select').innerHTML=simpleInvestmentIds.map(id=>'<option value="'+id+'">'+id.toUpperCase()+'</option>').join('');$('simple-stock-select').addEventListener('change',simpleStock);
$('plan-risk').value=plan.default_profile||'lower';
$('simple-stock-more').addEventListener('click',()=>{const id=$('simple-stock-select').value;if(R.filings[id]){$('financial-select').value=id;financialAsset();detailShow('financials')}else if(id==='nvda')detailShow('nvda');else detailShow('overview')});
['plan-risk','plan-deadline','plan-budget','plan-fx','plan-monthly'].forEach(id=>$(id).addEventListener('input',renderSimplePlan));$('simple-market-select').addEventListener('change',simpleMarkets);
renderSimplePlan();simpleMarkets();simpleShow('simple-plan');
